---
- name: write commercial authentication file for kubelet
  template:
    src: kubelet-auth.json.j2
    dest: /etc/crio/auth.json
  when: commercial.enabled

- name: make sure, registry is not set
  file:
    path: /etc/containers/registries.conf
    state: absent

- name: add container repos
  blockinfile:
    path: "{{ item }}"
    block: |
      [registries.search]
      registries = ['docker.io', 'registry.fedoraproject.org', 'registry.access.redhat.com', '{{ global.registry }}', 'k8s.gcr.io']
    create: true
  with_items:
    - /etc/containers/registries.conf
  when: commercial.enabled != true

- name: add container repos
  blockinfile:
    path: "{{ item }}"
    block: |
      [registries.search]
      registries = ['docker.io', 'registry.fedoraproject.org', 'registry.access.redhat.com', '{{ global.registry }}', '{{ commercial.registry.url }}', 'k8s.gcr.io']
    create: true
  with_items:
    - /etc/containers/registries.conf
  when: commercial.enabled

- name: remove cni configs
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/etc/cni/net.d/100-crio-bridge.conf"
    - "/etc/cni/net.d/200-loopback.conf"

- name: Make sure crio service is running 
  systemd:
    state: restarted
    enabled: true
    name: crio

- name: Make sure kubelet service is running
  systemd:
    state: restarted
    enabled: true
    name: kubelet

- name: Add modules
  modprobe:
    name: "{{ item }}"
    state: present    
  with_items:
     - br_netfilter
     - overlay
  
- name: make Modules persistant
  lineinfile:
    path: /etc/modules-load.d/k8s.conf
    line: "{{ item }}"      
    create: true
  with_items:
     - br_netfilter
     - overlay

- name: create bridge traffic config
  sysctl:
    name: "{{ item }}"
    value: '1'
    sysctl_file: /etc/sysctl.d/k8s.conf
    reload: yes
  with_items:
    - net.bridge.bridge-nf-call-ip6tables
    - net.bridge.bridge-nf-call-iptables
    - net.ipv4.ip_forward

# See https://github.com/cilium/cilium/issues/10645
- name: set net.ipv4.conf.*.rp_filter to 0 for systemd 245 workaround
  sysctl:
    name: "{{ item }}"
    value: '0'
    sysctl_file: /etc/sysctl.d/99-z-rp_filter.conf
    reload: yes
  with_items:
    - net.ipv4.conf.all.rp_filter
    - net.ipv4.conf.default.rp_filter

- name: Disable Swap
  command: swapoff -a

- name: Disable swap permanently, persist reboots
  replace:
    path: /etc/fstab
    regexp: '^(\s*)([^#\n]+\s+)(\w+\s+)swap(\s+.*)$'
    replace: '#\1\2\3swap\4'

- name: Persist swapoff
  template:
    src: ./templates/boot.local
    dest: /etc/init.d/boot.local
    mode: 0755
  when: ansible_os_family == 'Suse'

- name: "Reboot machine to get latest updates"
  reboot:
