---
- name: Include certificate var
  include_vars:
    file: /tmp/cluster_vars.yml
  # when: certificate_key is not defined or certificate_key|length <1
- debug:
    var: token

- name: define port, kubelet is listening on
  set_fact:
    apiport: "{% if create_extLB %}6443{% else %}8443{% endif %}"

- name: Join to Kubernetes cluster
  command: >
    kubeadm join --token {{ token }} --node-name {{ inventory_hostname_short }} \
                 --discovery-token-ca-cert-hash sha256:{{ ca_cert_hash }} \                                          
                 --control-plane api.{{ clusterTLDomain }}:6443 \
                 --certificate-key {{ certificate_key }} \
                 --apiserver-bind-port {{ apiport }}

