---
commercial:
  enabled: true
  username: "testUsername"
  key: "testKey"
make_ha: true
create_extLB: false
cluster_uuid: "ee582ffa-f6ba-11ea-adc1-0242ac120002"
cluster_pod_cidr: "10.0.0.0/8"
cluster_serv ice_cidr: "10.96.0.0/12"
staging_tag: "testing" 
# possible issuer: "letsencrypt-staging", "letsencrypt-prod" or "certmanager-selfsigned"
LE_issuer_name: "letsencrypt-staging" # tls.issuerName
LE_issuer_mail: "testing@test.vanillastack.cloudical.net" #tls.issuerEmail
loadbalancerIP: 135.181.48.19 # kubernetes.loadBlanacer.virtualIP
clusterTLDomain: test.vanillastack.cloudical.net # kubernetes.loadBlanacer.clusterDomain
reset_environment: false kubernetes.resetCluster
nextcloud_instancename: "nextcloud"
vanillaservices:
  dashboard_enabled: true # kubernetes.dashboard.enabled
  cloudfoundry_enabled: true # cloudfoundry.enabled
  nextcloud_enabled: true    
  stratos_enabled: true # stratos.enabled
  guacamole_enabled: true # guacamole.enabled
  pgOperator_enabled: true # postgresOperator.enabled
  redis_enabled: true # redis.enabled
  harbor_enabled: true # harbor.enabled
  loggingStack_enabled: true #efkstack.enabled
  monitoring_enabled: true # prometheus.enabled
  kubevirt_enabled: true # kubevirt.enabled
  moodle_enabled: false # moodle.enabled
  keycloak_enabled: true # keycloak.enabled
  openstack_enabled: false # openstack.enabled
vanillastorageprovider: "rook"
polyverse:
  enabled: false
  key: "testKey"
