---
openstack:
  enabled: true
  namespace: openstack
  publicDomain: "{{ kubernetes.loadBalancer.clusterDomain }}"
  publicProto: "http"
  region: RegionOne
  # releases available:
  # - stein (EOL 2020.11.11)
  # - train
  # - ussuri (not tested)
  release: "ussuri"
  tls:
    enabled: true
    useCertManager: true
    letsEncrypt:
      enabled: true
  mariadb:
    enabled: true
    chartName: mariadb
    chartVersion: 0.1.4
    createService: false
    replicas: 3
    persistence:
      enabled: true
      storageClass: "rook-ceph-block"
      diskSize: 30Gi
    auth:
      admin:
        password: nBR46Yx5oKoaORLdHXC675emg 
      sst:
        password: g1tCeWCl5JlnN4KfII2w1rjWD
      audit:
        password: MF91daYvdqnJSALlPNHa0y2ox
      exporter:
        password: KvK63FDIqTdCKrFiknVHCIVtC
  rabbitmq:
    enabled: true
    chartName: rabbitmq
    chartVersion: 0.1.1
    createService: false
    replicas: 2
    persistence:
      enabled: true
      storageClass: "rook-ceph-block"
      diskSize: 20Gi
    auth:
      admin:
        password: QaBQRbiSh7LVcmUfr066OxOoc
  memcached:
    enabled: true
    chartName: memcached
    chartVersion: 0.1.1
    createService: false
    replicas: 1
  ceph:
    enabled: true
    rook:
      namespace: "rook-ceph"
      fsid: "602a7124-e4ba-43fd-a6f7-00bd574329d8"
  barbican:
    enabled: true
    chartName: barbican
    chartVersion: 20201108
    createService: true
    api:
      replicas: 2
    endpoints:
      publicURLPrefix: "barbican"
    auth:
      service:
        password: WIyJB5ucjhRDBi7JDLN4xPsZF
      db:
        password: SLyl35ZTcLs1HSx1MLEEKrTo3
      messaging:
        password: ygj41kywzWQL0304n64C6bneW
  cinder:
    enabled: true
    chartName: cinder
    chartVersion: 20201108
    createService: true
    rbd:
      enabled: true
      rbdPool: cinder.volumes
      rbdUser: cinder
      rbdBackupUser: cinder-backup
      rbdBackupPool: cinder.backups
    api:
      replicas: 2
      v1Enabled: false
    volume:
      replicas: 1
      osapiVolumeWorkers: 1
    scheduler:
      replicas: 1
    backup:
      enabled: false
      replicas: 1
    endpoints:
      publicURLPrefix: "cinder"
    auth:
      service:
        password: Hb8M4cmki6BxsvgYZ4efBRfzN
      db:
        password: iyg1TU0Q6Kbe1GQ74cpIvP002
      messaging:
        password: r5L4CXlnthbhOqrvkgMmmV4Lx
      cinderTest:
        password: CsXVpYJ1isCfJ8Lu97CY25s7W
  congress:
    enabled: false
    chartName: congress
    chartVersion: 20201108
    createService: true
    api:
      replicas: 2
    policyEngine:
      replicas: 2
    datasource:
      replicas: 1
  designate:
    enabled: false
    chartName: designate
    chartVersion: 20201108
    createService: true
    auth:
      service: 
        password: WvusP3DVawNqM4VIhPsEhptyj
  glance:
    enabled: true
    chartName: glance
    chartVersion: 20201108
    createService: true
    defaultBackend: rbd
    rbd:
      enabled: true
      cephAppName: glance
      rbdPool: glance.images
      rbdUser: glance
      showImageDirectUrl: true
    api:
      replicas: 2
      v1Enabled: false
      version: 2
    registry:
      replicas: 2
      v2Enabled: true
    endpoints:
      publicURLPrefix: "glance"
    auth:
      service:
        password: L1hHckv7JulXzAWr2lCyKPwMp
      db:
        password: 83bpLt7JyuBNjLWjI1SPdrxex
      messaging:
        password: Vc1aHXgW79mz2xdXV7Yk7v1NB
      glanceTest:
        password: AkaQ342jULeq7sWV7ayT2bu6d
      radosgw:
        password: woK1JLHAz6SujFQsvoPMKm6wH
  heat:
    enabled: true
    chartName: heat
    chartVersion: 20201108
    createService: true
    api:
      replicas: 2
    cfn:
      replicas: 2
    cloudwatch:
      replicas: 2
    engine:
      replicas: 2
    endpoints:
      publicURLPrefix: "heat"
      cfnPublicURLPrefix: "heat-cfn"
    auth:
      service:
        password: Fv2ZXIEb5V5jZTpyA856vkJhB
      db:
        password: K29Kr9Uf2xJiovkixnWf4b27V
      messaging:
        password: 1R8B1FepIqiaqQrHVS0ncuXpP
      heatTest:
        password: Qcfl85lFlryeBzC9kU63sMy1e
      heatDomain:
        password: EQgwc4yPg855CdOrbpf1WbBxx
      serviceTrustee:
        password: nCWZSoGhojIJf0zKWS7V3t2mg
  horizon:
    enabled: true
    chartName: horizon
    chartVersion: 20201108
    createService: true
    replicas: 2
    endpoints:
      useDirectPublicDomain: false
      publicURLPrefix: "horizon"
    auth:
      db:
        password: 6jswYdW52JEN0y7oRZ8NLHwCq
  ironic:
    enabled: false
    chartName: ironic
    chartVersion: 20201108
    createService: true
    auth:
      service: 
        password: bC3FON5hMXFaJbAEDARV6EfBG
  keystone:
    enabled: true
    chartName: keystone
    chartVersion: 20201108
    createService: true
    endpoints:
      publicURLPrefix: "keystone"
    api:
      replicas: 2
    auth:
      admin:
        password: sn0JGJ2NXuBUrfyoHYRDnKNY3
      keystoneTest:
        password: zxQoRVj9dx3ghYDoeDtrIhaMt
      db:
        password: 1b2g39k10Qcs6QjugmOt7guPb
      messaging:
        password: CdvLDh2fp6WnciVxHsSnrWhOd
  libvirt:
    enabled: true
    chartName: libvirt
    chartVersion: 0.1.3
    createService: false
  mistral:
    enabled: true
    chartName: mistral
    chartVersion: 20201108
    createService: true
    api:
      replicas: 2
    engine:
      replicas: 2
    eventEngine:
      replicas: 2
    executor:
      replicas: 2
    endpoints:
      publicURLPrefix: "mistral"
    auth:
      service:
        password: P5nK12zDB5U93hSpistGtyEU4
      mistralTest:
        password: 1MYMa9AeaqhTSPQ7qotTU4Tu1
      db:
        password: 4rammB7aZCdEusubYnOK6PgJI
      messaging:
        password: vRK5KyiuRKxAjy8Z1ySDFuDGS
  neutron:
    enabled: true
    chartName: neutron
    chartVersion: 20201108
    createService: true
    extInterface: "enp3s0"
    tunnelInterface: "enp2s0"
    server:
      replicas: 2
    l3:
      ha: false
      maxAgentsPerRouter: 1
      haNetworkType: vxlan
      dhcpAgents: 2
    endpoints:
      publicURLPrefix: "neutron"
    auth:
      service:
        password: 1H4c6JURsRRDB6tl4FemkmKU3
      db:
        password: XoGM7g5N6Ft0qc8cHTBfvWwFb
      messaging:
        password: b45MH3eKVBnXoKEufojIPquEX
      neutronTest:
        password: 7bs4vXXfk58oea8txB1w8Atqu
  nova:
    enabled: true
    chartName: nova
    chartVersion: 20201108
    createService: true
    apiMetadata:
      replicas: 1
    placement:
      replicas: 2
    osapi:
      replicas: 2
    conductor:
      replicas: 2
    consoleauth:
      replicas: 2
    scheduler:
      replicas: 1
    novncproxy:
      replicas: 1
    endpoints:
      publicURLPrefix: "nova"
      novncURLPrefix: "novnc"
      placementURLPrefix: "placement"
    libvirt:
      # bare metal = kvm, VMs = qemu
      virtType: kvm
      # bare metal = host-passthrough or host-model, vm= none
      cpuMode: host-model
    auth:
      service:
        password: uYn4gU4AabT9YryEOGRLNNhQi
      db:
        password: Y1T83ux9qwYBSL0JagRY6zdus
      placement:
        password: X3hGdwQAb3uCF52Z2F2SmmIzk
      messaging:
        password: 1XT7LZT67Tai6jOhcL61oPU7p
      novaTest:
        password: 65dS7dG3YqGkDtlQ7RMKvl2Z2
  octavia:
    enabled: false
    chartName: octavia
    chartVersion: 20201108
    createService: true
    api:
      replicas: 2
    worker:
      replicas: 1
    housekeeping:
      replicas: 1
    endpoints:
      publicURLPrefix: "octavia"
    auth:
      service:
        password: tJ9IbvCcD1A9n0c7EVgSTlH0l
      db:
        password: Ve9wpsYuFjMwthJJdUGr8Jq8v
      messaging:
        password: hBCbkeyDzaZSkXVp6zUYB3649
      octaviaTest:
        password: GhZRI3GgFZAjhm2SiWmvAP97W
  openvswitch:
    enabled: true
    chartName: openvswitch
    chartVersion: 0.1.2
    createService: false
  placement:
    enabled: true
    chartName: placement
    chartVersion: 20201108
    createService: true
    endpoints:
      publicURLPrefix: "placement"
    api:
      replicas: 2
    auth:
      service:
        password: A2Ok9qgQCf1ZfK2f2LyqkCvdh
      db:
        password: Fn9G0ZbExTemElnj8vmcKjlqq
      messaging:
        password: bw9r6DosLd8uRNy58bDnb6ozo
  radosgw:
    enabled: false
    chartName: ceph-rgw
    chartVersion: 0.1.1
    createService: true
    endpoints:
      publicURLPrefix: "radosgw"
    auth:
      service:
        password: lZcmrMgCOYFWe662PQAGdpwAT
  rally:
    # IMPORTANT: enable Rally for testing only!
    enabled: false
    chartName: rally
    chartVersion: 20201108
    createService: false
    enabledTasks:
      - cinder
      - glance
      - heat
      - keystone
      # - magnum
      #- neutron
      - nova
      - senlin
    auth:
      service:
        password: u27quXoDJegu2QIWZnqxakP7G
      db:
        password: lnB2Dj3UpezGJ0F4n22pOraYT 
    storageClass: "rook-ceph-block"
  senlin:
    enabled: false
    chartName: senlin
    chartVersion: 20201108
    createService: true
    api:
      replicas: 2
    engine:
      replicas: 2
    endpoints:
      publicURLPrefix: "senlin"
    auth:
      service:
        password: I38z3W3AlcLKP7LEC97cK3O9x
      db:
        password: rCl1oRknvNxi9oP0cuF4Hd6lx
      messaging:
        password: s7uSI9fmGv47VM15wWC67hRpo
      senlinTest:
        password: oIRMBVj10GgJX8dSg6qmFBGGU
