rook:
  enabled: true
  namespace: rook-ceph
  common:
    enabled: true
  operator:
    enabled: true
    csiEnableCephFS: true
    csiEnableRBD: true
    csiEnableGRPC: true
  cluster:
    enabled: true
    image: ceph/ceph:v15.2.5-20200916
    name: rook-ceph
    dataHostDir: /var/lib/rook
    mon:
      count: 3
      allowMultiplePerNode: false
    dashboard:
      enabled: false
      ssl: true
    monitoring:
      enabled: false
    storage:
      useAllNodes: true
      useAllDevices: true
  storageClassRBD:
    enabled: true
    name: rook-ceph-block
    failureDomain: host
    poolName: replicapool
    replicaLevel: 3
    minSize: 2
  storageClassObject:
    enabled: false
  storageClassFile:
    enabled: false
  toolbox:
    enabled: true
    name: rook-ceph-tools
  objectStorage:
    enabled: false
    ingress:
      domain: s3.test.vanillastack.cloudical.net
      tls:
        enabled: true
        issuerName: "{{ tls.issuerName }}"
    name: cephobjectn1
    failureDomain: host
    replicaLevel: 2
    minSize: 1
  filesystem:
    enabled: false
    name: cephfsn1
    replicaLevel: 2
    failureDomain: host
    minSize: 1
