---
- name: get rook toolbox podname
  shell: kubectl get po -n {{openstack.ceph.rook.namespace}} |grep tool|cut -d' ' -f1
  register: rook_toolbox

- name: generate ceph etc configmap
  template:
    src: ./templates/ceph-etc-configmap.yaml.j2
    dest: /tmp/ceph-etc-configmap.yaml

- name: create configmap
  k8s:
    src: /tmp/ceph-etc-configmap.yaml 
    state: present

- name: cleanup ceph etc configmap 
  file:
    path: /tmp/ceph-etc-configmap.yaml
    state: absent

- name: generate ceph rgw etc configmap 
  template:
    src: ./templates/ceph-rgw-configmap.yaml.j2
    dest: /tmp/ceph-rgw-configmap.yaml

- name: create rgw configmap 
  k8s:
    src: /tmp/ceph-rgw-configmap.yaml
    state: present

- name: cleanup ceph rgw etc configmap 
  file:
    path: /tmp/ceph-rgw-configmap.yaml
    state: absent

- name: create admin keyring
  shell: echo "$(kubectl exec -ti -n {{openstack.ceph.rook.namespace}} {{rook_toolbox.stdout}} -- ceph auth get-or-create client.admin|grep key|tr -s " "|cut -d" " -f3)" >/tmp/openstack-ceph-admin

- name: create admin keyring secret
  shell: kubectl create secret generic pvc-ceph-client-key --type=kubernetes.io/rbd -n {{openstack.namespace}} --from-file=key=/tmp/openstack-ceph-admin
  ignore_errors: true

- name: delete temp keyring file
  file:
    path: /tmp/openstack-ceph-admin
    state: absent

- name: create glance rbd pool
  shell: kubectl exec -ti -n {{openstack.ceph.rook.namespace}} {{rook_toolbox.stdout}} -- ceph osd pool create {{openstack.glance.rbd.rbdPool}} 8 8
  ignore_errors: true

- name: create glance rbd pool application
  shell: kubectl exec -ti -n {{openstack.ceph.rook.namespace}} {{rook_toolbox.stdout}} -- ceph osd pool application enable {{openstack.glance.rbd.rbdPool}} rbd
  ignore_errors: true

- name: create glancee ceph user
  shell: echo "$(kubectl exec -ti -n {{openstack.ceph.rook.namespace}} {{rook_toolbox.stdout}} -- ceph auth get-or-create client.{{openstack.glance.rbd.rbdUser}} mon "profile rbd" osd "profile rbd pool={{openstack.glance.rbd.rbdPool}}" mgr "profile rbd pool={{openstack.glance.rbd.rbdPool}}"|grep key|tr -s " "|cut -d" " -f3)">/tmp/openstack-ceph-glance
  ignore_errors: true

- name: create glance ceph user secret
  shell: kubectl create secret generic images-rbd-keyring --type=kubernetes.io/rbd -n {{openstack.namespace}} --from-file=key=/tmp/openstack-ceph-glance
  ignore_errors: true

- name: cleanup glance ceph user
  file:
    path: /tmp/openstack-ceph-glance
    state: absent

- name: create cinder volume pool
  shell: kubectl exec -ti -n {{openstack.ceph.rook.namespace}} {{rook_toolbox.stdout}} -- ceph osd pool create {{openstack.cinder.rbd.rbdPool}} 8 8
  ignore_errors: true

- name: create cinder backup pool
  shell: kubectl exec -ti -n {{openstack.ceph.rook.namespace}} {{rook_toolbox.stdout}} -- ceph osd pool create {{openstack.cinder.rbd.rbdBackupPool}} 8 8
  ignore_errors: true

#- name: create cinder rbd pool application
#  shell: kubectl exec -ti -n {{openstack.ceph.rook.namespace}} {{rook_toolbox.stdout}} -- ceph osd pool application enable {{openstack.cinder.rbd.rbdPool}} rbd
#  ignore_errors: true
#
#- name: create cinder backup  rbd pool application
#  shell: kubectl exec -ti -n {{openstack.ceph.rook.namespace}} {{rook_toolbox.stdout}} -- ceph osd pool application enable {{openstack.cinder.rbd.rbdBackupPool}} rbd
#  ignore_errors: true

- name: create cinder ceph user
  shell: echo "$(kubectl exec -ti -n {{openstack.ceph.rook.namespace}} {{rook_toolbox.stdout}} -- ceph auth get-or-create client.{{openstack.cinder.rbd.rbdUser}} mon "profile rbd" osd "profile rbd pool={{openstack.cinder.rbd.rbdPool}}, profile rbd pool={{openstack.cinder.rbd.rbdBackupPool}}, profile rbd-read-only pool={{openstack.glance.rbd.rbdPool}}" mgr "profile rbd pool={{openstack.cinder.rbd.rbdPool}}, profile rbd pool={{openstack.cinder.rbd.rbdBackupPool}}"|grep key|tr -s " "|cut -d" " -f3)">/tmp/openstack-ceph-cinder
  ignore_errors: true

- name: create cinder volume keyring secret
  shell: kubectl create secret generic cinder-volume-rbd-keyring --namespace={{openstack.namespace}} --type=kubernetes.io/rbd --from-file=key=/tmp/openstack-ceph-cinder
  ignore_errors: true

- name: create cinder rbd volume keyring secret
  shell: kubectl create secret generic volumes-rbd-keyring --namespace={{openstack.namespace}} --type=kubernetes.io/rbd --from-file=key=/tmp/openstack-ceph-cinder
  ignore_errors: true

- name: cleanup ceph-cinder
  file:
    path: /tmp/openstack-ceph-cinder
    state: absent
