---
- name: Create namespace
  k8s:
    name: "{{openstack.namespace}}"
    api_version: v1
    kind: Namespace
    state: present
  when: openstack.enabled

- name: Create LetsEncrypt Issuer
  include_tasks: clusterissuer.yaml
  when: openstack.tls.useCertManager and openstack.enabled

- name: Deploy ceph connnector
  include_tasks: ceph-connector.yaml
  when: openstack.enabled

- name: Enable TLS
  when: openstack.tls.enabled and openstack.enabled
  include_tasks: tls.yaml

- name: Deploy OpenStack
  include_tasks: deploy.yaml
  when: openstack.enabled
  with_items:
    - { name: mariadb, wait: true}
    - { name: rabbitmq, wait: true}
    - { name: memcached, wait: true}
    - { name: keystone, wait: true}
    - { name: horizon, wait: true}
    - { name: glance, wait: true}
    - { name: cinder, wait: true}
    - { name: openvswitch, wait: true}
    - { name: neutron, wait: false}
    - { name: libvirt, wait: false}
    - { name: placement, wait: false}
    - { name: nova, wait: true}
    - { name: heat, wait: true}
    - { name: radosgw, wait: true}
    - { name: barbican, wait: true}
    - { name: senlin, wait: true}
    - { name: mistral, wait: true}
    - { name: congress, wait: true}
    - { name: octavia, wait: true}
    - { name: rally, wait: false }
