efkstack:
  enabled: true
  imageTag: "7.9.1"
  kibana:
    user: kibana_test
    password: secretlysecretpassword
    replicas: 2
    system_user: "{{ ansible_user }}"
    coreDomain: "kibana.{{ kubernetes.loadBalancer.clusterDomain }}"
    resources:
      requests:
        cpu: "200m"
        memory: "1Gi"
      limits:
        cpu: "1000m"
        memory: "2Gi"
  es:
    replicas: 3
    storage:
      class_name: "rook-ceph-block"
      size: "30Gi"
    resources:
      requests:
        cpu: "200m"
        memory: "2Gi"
      limits:
        cpu: "1000m"
        memory: "2Gi"
  logaggregator:
    # Choice of filebeat and fluentd
    name: filebeat
    resources:
      limits:
        cpu: "500m"
        memory: "512Mi"
      requests:
        cpu: "100m"
        memory: "200Mi"
