---
- name: create folder for config
  hosts: localhost
  vars:
    ansible_connection: local
  tasks:
    - name: make sure local uuid directory exists
      file:
        state: directory
        path: "/tmp/ansible/{{ global.uuid }}"
        recurse: yes
      register: success
      failed_when: success
