---
- name: Deploy OpenStack
  hosts: master[0]
  become: false
  gather_facts: no
  roles:
#    - role: prepare-node
#    - role: helm-nginx-ingress
    - role: deploy-openstack
  when: openstack.enabled
