---
# defaults file for install-guacamole
guacamole:
  imageTag: latest
  enabled: false
  namespace: guacamole
  postgres:
    maxConnections: 400
    backup:
      enabled: false
      cronjob: "30 */2 * * *"
    version: "12"
    replicas: "2"
    size: "20Gi"
